### ISSUE TITLE
显示的时候, 最上面有遮挡

### ISSUE THREAD

**Issue by chang-shuai** [carlos-wong/cerebro-yasyoudao#2]
显示有点小问题, 搜索一个词, 在结果页的最上面被遮挡了

**Comment by carlos-wong** [comment]
![image](https://user-images.githubusercontent.com/1055130/42554180-78b8f2c4-8516-11e8-877a-d5a0aaa764f3.png)

@chang-shuai 能提供一个截图吗？类似我上面传的这张图，最好能标记一下遮挡的位置。

**Comment by carlos-wong** [comment]
@chang-shuai https://github.com/carlos-wong/cerebro-yasyoudao/commit/f5db07b988de565f56d8dd1cb12ad96db49349bf
